server.port=8081
spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/bd_arabe
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
gemini.api.key=AQ.Ab8RN6IvsLfNMBvIB36LAHbU35V1FvpnIMvN0EzGknBFdW7flQ
